### ISSUE TITLE
Exception list error...

### ISSUE THREAD

**Issue by FlavioSerini** [mfreiholz/iF.SVNAdmin#101]
Hello Manuel, 

I installed iF.SVNadmin, and I'm facing the error below when I click on repositories->list-><myrepository>

"Exception list XML parse error: (code=5) Invalid document end"

I'm using RHEL6.4/php-5.6.10/subversion-1.8.9

Reading others issues, I already checked 

- apache user does have write permission on my repository parent directory
- SELinux is disabled
- My path are pointing correctly to executable svn | svnadmin 

Can i missing anything?
Any help would be appriciated.
Thanks in advance.

Flavio Serini

**Comment by mfreiholz** [comment]
Hi,

does your repostiory names contain any special characters (Russian, Chinese, ...)?
You might also check the apache error log file.

Manuel

**Comment by FlavioSerini** [comment]
Thanks for your quick response.

Answer your questions. 

No, my repository name is "seriniteste" on file system "/app/svn/seriniteste/"

Apache logs don´t tell me much things...

- 10.14.16.9 - - 700042 [20/Jul/2015:10:02:57 -0300] "GET /svnadmin/repositoryview.php?pi=0&r=seriniteste HTTP/1.1" 500 3467 "http://subversion-hom.pernambucanas.intranet/svnadmin/repositorylist.php" "Mozilla/5.0 (Windows NT 5.1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/43.0.2357.134 Safari/537.36" text/html

[Mon Jul 20 10:02:57 2015] [error] [client 10.14.16.9] PHP Fatal error:  Call to a member function getEncodedParentIdentifier() on null in /u01/hom/binarios/svnadmin/pages/repository/repositoryview.html.php on line 5, referer: http://subversion-hom.pernambucanas.intranet/svnadmin/repositorylist.php


My apache conf below... a guess it's ok.. 
I have a master config that call an include.

Config master

<VirtualHost 10.14.16.44:80>
    ServerName subversion-hom.company.intranet
    DocumentRoot /u01/hom/binarios/apache-2.2.26/htdocs/svn/
    DirectoryIndex index.html

    <Location "/">
        AuthBasicProvider ldap
        AuthType Basic
        AuthzLDAPAuthoritative off
        AuthName "Subversion - Ldap server"
        AuthLDAPURL "ldap://authldap.company.intranet:389/ou=company,DC=company,DC=intranet?sAMAccountName?sub?(objectClass=*)" NONE
        AuthLDAPBindDN "CN=mnsubversion,OU=SERVICOS,DC=company,DC=intranet"
        AuthLDAPBindPassword ************
            require valid-user
     </Location>

     include conf/mds/repositorios/*.conf

    CustomLog "|/u01/hom/binarios/apache-2.2.26/bin/rotatelogs /u01/hom/logs/apache/subversion-hom.company.intranet/access_log-%Y-%m-%d-%H_%M_%S 20M" combined
    ErrorLog "| /u01/hom/binarios/apache-2.2.26/bin/rotatelogs /u01/hom/logs/apache/subversion-hom.company.intranet/error_log-%Y-%m-%d-%H_%M_%S 20M"

</VirtualHost>


Alias /svnadmin "/u01/hom/binarios/svnadmin"

<Directory "/u01/hom/binarios/svnadmin">
    DirectoryIndex index.php
    Options Indexes
    AllowOverride None
    Order allow,deny
    Allow from all
</Directory>


Here the include

<Location "/seriniteste">
        DAV svn
        SVNParentPath /app/svn/seriniteste
        SVNListParentPath on
        AuthzSVNAccessFile "/app/svn/seriniteste/conf/authz"
</Location>

I'm working with 
- apache-2.2.26
- php-5.6.10
- subversion-1.8.9

Thanks for your help.
Best regards

**Comment by mfreiholz** [comment]
Hm.. maybe its a problem with subversion 1.8 and it's XML format.
I will check this in a moment.

**Comment by mfreiholz** [comment]
I just checked it with svn 1.8.13 on Windows and it works fine.

Another problem could be the general encoding of the Linux command line, but i currently don't know how to change it.

Never tested in on a RHEL machine :-/

**Comment by FlavioSerini** [comment]
No problem, I'll check it with svn 1.8.13 and tell you later.

**Comment by mfreiholz** [comment]
Hm, can't imaging that it matter.
In which language/locale does your linux machine run? English?

**Comment by FlavioSerini** [comment]
Yeap...minor version doesn't change nothing...same error.
LANG=en_US.UTF-8

**Comment by mfreiholz** [comment]
Hm.. can you add the following code:

```
error_log($command);
```

here:

https://github.com/mfreiholz/iF.SVNAdmin/blob/master/include/ifcorelib/IF_SVNClientC.class.php#L135

It should log the used command into apache error log. You can then try to run this command by yourself on console.

**Comment by FlavioSerini** [comment]
Here's return error log

[Mon Jul 20 14:39:32 2015] [error] [client 10.14.16.9] "/u01/hom/binarios/subversion/bin/svn" ls --xml --non-interactive --trust-server-cert file:///app/svn//seriniteste/, referer: http://subversion-hom.pernambucanas.intranet/svnadmin/repositorylist.php
[Mon Jul 20 14:39:32 2015] [error] [client 10.14.16.9] PHP Fatal error:  Call to a member function getEncodedParentIdentifier() on null in /u01/hom/binarios/svnadmin/pages/repository/repositoryview.html.php on line 5, referer: http://subversion-hom.pernambucanas.intranet/svnadmin/repositorylist.php

**Comment by mfreiholz** [comment]
Ah great and what happens when you execute the command in your console?

`"/u01/hom/binarios/subversion/bin/svn" ls --xml --non-interactive --trust-server-cert file:///app/svn//seriniteste/`

Does it work? Or better, post the output please :P

**Comment by FlavioSerini** [comment]
ops.. I forgot the second part... sorry..

I tried with and without those slash "///"

[oraias@svblec23 subversion-hom.pernambucanas.intranet]$ "/u01/hom/binarios/subversion/bin/svn" ls --xml --non-interactive --trust-server-cert file:///app/svn//seriniteste/
<?xml version="1.0" encoding="UTF-8"?>
<lists>
<list
   path="file:///app/svn/seriniteste">
svn: E180001: Unable to connect to a repository at URL 'file:///app/svn/seriniteste'
svn: E180001: Unable to open an ra_local session to URL
svn: E180001: Unable to open repository 'file:///app/svn/seriniteste'

### without //
[oraias@svblec23 subversion-hom.pernambucanas.intranet]$ "/u01/hom/binarios/subversion/bin/svn" ls --xml --non-interactive --trust-server-cert file:/app/svn/seriniteste
<?xml version="1.0" encoding="UTF-8"?>
<lists>
<list
   path="file:/app/svn/seriniteste">
svn: E155007: '/u01/hom/logs/apache/subversion-hom.pernambucanas.intranet/file:/app/svn/seriniteste' is not a working copy
[oraias@svblec23 subversion-hom.pernambucanas.intranet]$

But in nowhere are configured "///"
![image](https://cloud.githubusercontent.com/assets/13365114/8783797/72c74116-2ef4-11e5-8a48-b16e2eda2331.png)

**Comment by mfreiholz** [comment]
Ah.. its a permission problem as far as i can remember. You need to define a custom svn-config-dir. You can do that by uncommenting the following line:
https://github.com/mfreiholz/iF.SVNAdmin/blob/master/include/config.inc.php#L50

Use your own valid path here, maybe inside the app directory `<svnadmin>/data/svnconfig` and create the directory by yourself and assign CHMOD 777 to it.

**Comment by mfreiholz** [comment]
Btw.. you don't need an ending slash for "SVNParentPath".

**Comment by FlavioSerini** [comment]
hahaha Totally weird... thanks btw

IT WORKS!!! with custom svn-config-dir.  

Just let you know,  work with 755 on parent directory of the repositories. 

Manuel, I am very grateful for your help. 

Best regards.

**Comment by mfreiholz** [comment]
Great! Thanks for your patience ;)

**Comment by tonglv** [comment]
[Wed Jan 03 16:23:42.410064 2018] [:error] [pid 26262] [client 10.165.11.82:60422] PHP Fatal error:  Call to a member function getEncodedParentIdentifier() on a non-object in /apps/www/html/svnadmin/pages/repository/repositoryview.html.php on line 5, referer: http://10.167.202.199/svnadmin/repositorylist.php
[Wed Jan 03 16:23:54.715564 2018] [:error] [pid 26263] [client 10.165.11.82:60427] PHP Fatal error:  Call to a member function getEncodedParentIdentifier() on a non-object in /apps/www/html/svnadmin/pages/repository/repositoryview.html.php on line 5, referer: http://10.167.202.199/svnadmin/repositorylist.php
[Wed Jan 03 16:26:39.792492 2018] [:error] [pid 26265] [client 10.165.11.82:60488] PHP Fatal error:  Call to a member function getEncodedParentIdentifier() on a non-object in /apps/www/html/svnadmin/pages/repository/repositoryview.html.php on line 5, referer: http://10.167.202.199/svnadmin/repositorylist.php

**Comment by yangzzq** [comment]
在浏览代码仓库的时候报错XML parse error: (code=5) Invalid document end
parent directory of the repositories is /opt/svn

define("IF_SVNBaseC_ConfigDir", "/opt/svn");
and 
chmod 755 with /opt/svn
it dose not work 
who can tell me why@mfreiholz @FlavioSerini
