### ISSUE TITLE
AJAX Error while Test LDAP settings

### ISSUE THREAD

**Issue by pdagorn** [mfreiholz/iF.SVNAdmin#103]
Hello,
The last master give those red errors while I was testing settings for ldap user and for ldap groups (it worked perfectly with the last release package)

AJAX Error:
jqXHR=[object XMLHttpRequest]
textStatus=error;
errorThrown=undefined;

Thank you!

**Comment by gubik89** [comment]
I also have this error. There is a solution?

**Comment by mfreiholz** [comment]
Can you check your apache logs for errors, please?

Sent from mobile phone.
Am 26.08.2015 2:15 nachm. schrieb "gubik89" <notifications@github.com>:

**Comment by gubik89** [comment]
Fatal error:  Class svnadmin\\providers\\ldap\\LdapUserViewProvider contains 3 abstract methods and must therefore be declared abstract or implement the remaining methods (svnadmin\\core\\interfaces\\IGroupViewProvider::getGroupsOfSubgroup, svnadmin\\core\\interfaces\\IGroupViewProvider::getSubgroupsOfGroup, svnadmin\\core\\interfaces\\IGroupViewProvider::isSubgroupInGroup) in /var/www/svnadmin1.6.2/classes/providers/ldap/LdapUserViewProvider.class.php on line 884, referer: http://192.168.101.25/svnadmin1.6.2/settings.php

**Comment by mfreiholz** [comment]
Hm thats weird. Which version do you use?


Best,
Manuel

Checkout some of my work
Projects: TS3VIDEO <http://ts3video.insanefactory.com>, HumbleLogging
<http://humblelogging.insanefactory.com>, iF.SVNAdmin
<http://svnadmin.insanefactory.com>
Websites: insaneFactory <http://www.insanefactory.com>


2015-08-26 15:22 GMT+02:00 gubik89 <notifications@github.com>:

**Comment by gubik89** [comment]
Hi.
problem solved
I used iF.SVNAdmin <<http://svnadmin.insanefactory.com>>. "Download Trunk" setup of man. Established svnadmyn1.6.3 .
 > I downloaded the stable1.6.2 installed. Working. 

Thank you.

**Comment by nkhdiscovery** [comment]
Hi,
I'm facing the same problem but I can't understand the previous answer, there is no version 1.6.3, the latest stable version on master branch is the 1.6.2 which has this problem. I think you should re-open this issue.

**Comment by mfreiholz** [comment]
Can you try the current master and try it, please?

**Comment by nkhdiscovery** [comment]
I just did, it happens with the current master.

**Comment by nkhdiscovery** [comment]
I found this in log when it occurs, it may help: (latest master)

[Wed Mar 02 09:46:01.573332 2016] [php5:error] [pid 22573] [client 192.168.30.172:46060] PHP Fatal error:  Class svnadmin\\providers\\ldap\\LdapUserViewProvider contains 3 abstract methods and must therefore be declared abstract or implement the remaining methods (svnadmin\\core\\interfaces\\IGroupViewProvider::getGroupsOfSubgroup, svnadmin\\core\\interfaces\\IGroupViewProvider::getSubgroupsOfGroup, svnadmin\\core\\interfaces\\IGroupViewProvider::isSubgroupInGroup) in /var/www/virtualHosts/faraadid.com/subdomains/svnadmin/classes/providers/ldap/LdapUserViewProvider.class.php on line 884, referer: http://svnadmin.faraadid.com/settings.php

**Comment by nkhdiscovery** [comment]
It seems you have forgotten to implement three functions added in ./classes/core/interfaces/IGroupViewProvider.iface.php, in the class ./classes/providers/ldap/LdapUserViewProvider.class.php, which are getGroupsOfSubgroup, getSubgroupsOfGroup and isSubgroupInGroup, if I'm not wrong.

**Comment by mfreiholz** [comment]
Ah yes.. Seems like the current master is not good for LDAP usage :-/

**Comment by spriggan-chen** [comment]
You can try.
dnf install php-json
