### ISSUE TITLE
Installation error on Synology NAS

### ISSUE THREAD

**Issue by voltige** [mfreiholz/iF.SVNAdmin#104]
Hello

I try to install iF.SVNAdmin on a Synology NAS.
The operating system is a derivative from linux.

I encounter errors when I type the pathname of svn.

![image](https://cloud.githubusercontent.com/assets/6236785/8953193/0d9fae64-35dd-11e5-8a14-7d7045c39d43.png)

Thank you

**Comment by mfreiholz** [comment]
Hi Voltige,

i found a similar problem with of another application, which solved the problem by editing the file `/usr/syno/etc/php/user-setting.ini`.

Adding the entry `/var/packages/SVN/target/bin/` to the `open_basdir` directive might help.

Greetings
Manuel

**Comment by voltige** [comment]
Hello,

I followed your recommendation.

I added the following paths to open_basedir:

- /var/packages/SVN/target/bin/
- the folder containing the svn repositories.
In my case this folder is "/volume1/svn"

![selection_025](https://cloud.githubusercontent.com/assets/6236785/8981171/754b253c-36b6-11e5-9ce7-2ff244f65196.png)

![selection_027](https://cloud.githubusercontent.com/assets/6236785/8981209/c0c2f698-36b6-11e5-8a0e-5e42a3159445.png)



Thank you so much
