### ISSUE TITLE
在浏览代码仓库的时候报错XML parse error: (code=5) Invalid document end

### ISSUE THREAD

**Issue by kys1230** [mfreiholz/iF.SVNAdmin#106]
日志的信息是这样的
[Tue Aug 25 13:59:00 2015] [error] [client 192.168.6.45] PHP Fatal error:  Call to a member function getEncodedParentIdentifier() on a non-object in /var/www/svnadmin/pages/repository/repositoryview.html.php on line 5, referer: http://192.168.5.202:89/repositorylist.php

**Comment by mfreiholz** [comment]
Everything else works fine? Its just the browsing, after you clicked on a repository?

**Comment by kys1230** [comment]
Yes, other functions can be used, but can not browse and add repository

**Comment by mfreiholz** [comment]
Uncomment the following line and insert a valid path:
https://github.com/mfreiholz/iF.SVNAdmin/blob/master/include/config.inc.php#L50

**Comment by mfreiholz** [comment]
Same solution in issue #101

**Comment by kys1230** [comment]
我的问题解决了.. 由于snv目录权限问题导致的无法浏览 .

**Comment by tonglv** [comment]
这个最终是怎么解决的。要什么权限，
5、(Svnadmin)Exception list XML parse error…..
web（IE）网页使用svnadmin管理工具时，浏览【代码仓库】出现异常：
Exception list 
XML parse error: (code=5) Invalid document end 
<a href="repositoryview.php?pi= 
Fatal error: Call to a member function getEncodedParentIdentifier() on a non-object in 
/usr/local/apache2/htdocs/iF.SVNAdmin-stable-1.6.2/pages/repository/repositoryview.html.php on line 5

//define("IF_SVNBaseC_ConfigDir", "E:/Development/Test/temp svnadmin/svn-config-dir"); 
define("IF_SVNBaseC_ConfigDir", "/blubb/edi/blubb");
我按这个方式，也没有解决。权限要怎么设置呢？
