### ISSUE TITLE
Create User removes the [Users]  Section header

### ISSUE THREAD

**Issue by RaNd250** [mfreiholz/iF.SVNAdmin#109]
After a new user is created svn logs  line 1: Section header expected

I found that the create user command deletes the first row in the svnserve_auth_file

**Comment by mfreiholz** [comment]
Yes, because the application is not supposed to work with svnserve. It only works in combination with Apache. Which uses a separate users file (.passwd or LDAP).

Here is a tutorial on how to configure the correct environment.
http://svnbook.red-bean.com/en/1.7/svn.serverconfig.httpd.html

**Comment by RaNd250** [comment]
Thnx.
I used this in a shell script called add_users_line.sh
```
sed -i '1s/^/[users] \n/' svnserve_auth_file
```
And i monitor the file with this in another script 
```
while true; do
  change=$(inotifywait -e close_write,moved_to,create .)
  change=${change#./ * }
  if [ "$change" = "svnserve_auth_file" ]; then ./add_users_line.sh; fi
done
```

Hope is helps someone and btw thanks for the great job on iF.SVNAdmin
