### ISSUE TITLE
There is no del button on the page "Repository management"

### ISSUE THREAD

**Issue by huanying061803** [mfreiholz/iF.SVNAdmin#113]
![1 -](https://cloud.githubusercontent.com/assets/3530348/12502778/de12b748-c107-11e5-9b22-9d09c33cea3e.png)

**Comment by mfreiholz** [comment]
You need to enable it in the configuration file:

```ini
[GUI]
# Allows the deletion of repositories via GUI.
# Set this to "false", if you don't want to allow the deletion of repositories in iF.SVNAdmin GUI.
RepositoryDeleteEnabled=false
```

**Comment by huanying061803** [comment]
great！it's ok now ，Thank you！！

**Comment by huanying061803** [comment]
great！it's ok now ，Thank you！！

**Comment by huanying061803** [comment]
great！it's ok now ，Thank you！！

**Comment by huanying061803** [comment]
great ! it's ok now , thank you !




-------------------------------------------------------------
2016-01-22



在2016年01月22 13时08分, "Manuel Freiholz"<notifications@github.com>写道:



You need to enable it in the configuration file:

[GUI]# Allows the deletion of repositories via GUI.# Set this to "false", if you don't want to allow the deletion of repositories in iF.SVNAdmin GUI.RepositoryDeleteEnabled=false
