### ISSUE TITLE
Restore admin password

### ISSUE THREAD

**Issue by KueWW** [mfreiholz/iF.SVNAdmin#114]
Hi,

I'm very sorry to ask that question.
How can I restore the admin password?

Thanks for help

**Comment by mfreiholz** [comment]
Are u using passwd based authentication?

the GUI does not provide a reset function. you can use the apache htpasswd
command line tool to set a new password.

Sent from mobile phone.
Am 24.03.2016 22:49 schrieb "KueWW" <notifications@github.com>:

**Comment by KueWW** [comment]
Yes I'm using passwd based authentication.
I'm using OpenSuse and tried the htpasswd2 command already. But it doesn't work. Which file do I have to use?

**Comment by mfreiholz** [comment]
You can add this __admin__ user with password __admin__ to your _passwd_ file and login to change the password of your real user.
```
admin:$apr1$cvmh/fto$nncvV9rDD7sbzxhc0bXhS1
```
You also need to give him administrator rights by defining it in your `data/userroleassignments.ini`file
```ini
[admin]
Administrator=
```
Let me know if it works :-)

**Comment by mfreiholz** [comment]
> Yes I'm using passwd based authentication.
I'm using OpenSuse and tried the htpasswd2 command already. But it doesn't work. Which file do I have to use?

You probably forgot to assign a role in `data/userroleassignments.ini` to your created user, which is required to login.

**Comment by KueWW** [comment]
I'm sorry. It didn't work. But I'm not sure if I use the right passwd files.
In the attachement you'll fin my config. I tried the admin settings with the default apache passwd file in /etc/apache2/htpasswd/default.pwd and in /etc/svn/svn-htpasswd as it is defined in my config.
[config.txt](https://github.com/mfreiholz/iF.SVNAdmin/files/189494/config.txt)

**Comment by mfreiholz** [comment]
Did you try it without the `file://` prefix for paths in _config.ini_?

**Comment by mfreiholz** [comment]
Hm.. i just tried it with file:// on my server and it works :-/

Do you have SElinux running on your machine? It sometimes permits access on files for PHP based applications.

**Comment by KueWW** [comment]
I'm runnig openSUSE 13.1 on my system.
Basically SVNADMIN is running. There are different users working. I just forget the password for admin.
There is another user with admin rights with which a can log in.

**Comment by KueWW** [comment]
Without "file://" the test says: "The file does not exist"

**Comment by KueWW** [comment]
Checking the admins password using 'htpasswd2 /etc/svn/svn-htpasswd admin' says that my password is correct.
Apaches (wwwrun:www) has the right to access the file.

**Comment by KueWW** [comment]
I've recreated the user admin with my second admin. Now it seems to work......
