### ISSUE TITLE
Unable to login for help

### ISSUE THREAD

**Issue by 501956430** [mfreiholz/iF.SVNAdmin#128]
Unable to log in after saving the configuration Save configration and return to the login page without any error
  httpd error log：
<img width="600" alt="2017-01-17 11 11 52" src="https://cloud.githubusercontent.com/assets/20204491/22025988/61f39bf8-dd0a-11e6-9f5e-b453f9a534fe.png">

<img width="1420" alt="2017-01-17 11 09 00" src="https://cloud.githubusercontent.com/assets/20204491/22025852/01e05f76-dd0a-11e6-80a0-6cbd16995f14.png">

**Comment by 501956430** [comment]
Who can help me Thank

**Comment by mfreiholz** [comment]
Looks like a general problem with your PHP configuration. Make sure that your apache server (probably the `www-data`user) does have the permission to write session files.

**Comment by 501956430** [comment]
@mfreiholz  Has been resolved, thank you
