### ISSUE TITLE
Config web interface

### ISSUE THREAD

**Issue by armandoroque1** [mfreiholz/iF.SVNAdmin#133]
Hi,

Can You help me?  

Web interface report:

Found 1 users.
Found 0 groups.

[Hosts]
	Windows 2012 - AD

	Oracle Linux 7.3
		[root@linux ~]# rpm -qa | grep http
			httpd-2.4.6-45.0.1.el7_3.4.x86_64
			httpd-tools-2.4.6-45.0.1.el7_3.4.x86_64
		[root@linux ~]# rpm -qa | grep php
			php-5.4.16-42.el7.x86_64
			php-ldap-5.4.16-42.el7.x86_64
			php-common-5.4.16-42.el7.x86_64
			php-cli-5.4.16-42.el7.x86_64
		[root@linux ~]# rpm -qa | grep ldap
			apr-util-ldap-1.5.2-6.0.1.el7.x86_64
			php-ldap-5.4.16-42.el7.x86_64
			openldap-2.4.40-13.el7.x86_64
			mod_ldap-2.4.6-45.0.1.el7_3.4.x86_64

AD - 
	CN=Users,DC=dominio,DC=floresta,server.dominio.floresta [server.dominio.floresta]
	
	Name				Type		Description
	Administrator		User		Built-in account for administering the computer/domain
	Armando AR. Roque	User
	autent1				User
	Guest				User		Built-in account for guest access to the computer/domain,
	sistema1			Security Group - Global
	user1s1 user1s1		User

[root@linux ~]# ls -la /var/www/html/svnadmin/
	total 156
	drwxr-xr-x  9 apache apache  4096 Apr 25 13:36 .
	drwxr-xr-x  3 root   root      36 Apr 24 18:19 ..
	-rw-r--r--  1 apache apache  1482 Apr 19 17:29 accesspathcreate.php
	-rw-r--r--  1 apache apache  2518 Apr 19 17:29 accesspathslist.php
	-rw-r--r--  1 apache apache  2521 Apr 19 17:29 accesspathview.php
	drwxr-xr-x  2 apache apache  4096 Apr 19 17:29 actions
	drwxr-xr-x  5 apache apache    71 Apr 19 17:29 classes
	-rw-r--r--  1 apache apache  2557 Apr 19 17:29 cli.php
	drwxrwxrwx  2 apache apache    77 Apr 25 16:11 data
	-rw-r--r--  1 apache apache  1280 Apr 19 17:29 error.php
	-rw-r--r--  1 apache apache  1061 Apr 19 17:29 groupcreate.php
	-rw-r--r--  1 apache apache  1250 Apr 19 17:29 grouplist.php
	-rw-r--r--  1 apache apache  2828 Apr 19 17:29 groupview.php
	drwxr-xr-x  3 apache apache    43 Apr 19 17:29 include
	-rw-r--r--  1 apache apache  1193 Apr 19 17:29 index.php
	-rw-r--r--  1 apache apache 18092 Apr 19 17:29 license.txt
	-rw-r--r--  1 apache apache  1324 Apr 19 17:29 login.php
	-rw-r--r--  1 apache apache   991 Apr 19 17:29 logout.php
	drwxr-xr-x 10 apache apache  4096 Apr 19 17:29 pages
	-rw-r--r--  1 apache apache  2541 Apr 19 17:29 permissionassign.php
	-rw-r--r--  1 apache apache   735 Apr 19 17:29 readme.md
	-rw-r--r--  1 apache apache  1259 Apr 19 17:29 repositorycreate.php
	-rw-r--r--  1 apache apache  2362 Apr 19 17:29 repositorylist.php
	-rw-r--r--  1 apache apache  3306 Apr 19 17:29 repositoryview.php
	-rw-r--r--  1 apache apache   402 Apr 19 17:29 rolelist.php
	-rw-r--r--  1 apache apache 21318 Apr 19 17:29 settings.php
	drwxr-xr-x  5 apache apache  4096 Apr 19 17:29 templates
	drwxr-xr-x  5 apache apache    58 Apr 19 17:29 translations
	-rw-r--r--  1 apache apache  1173 Apr 19 17:29 update.php
	-rw-r--r--  1 apache apache   815 Apr 19 17:29 userchangepass.php
	-rw-r--r--  1 apache apache  1076 Apr 19 17:29 usercreate.php
	-rw-r--r--  1 apache apache  1937 Apr 19 17:29 usergroupassign.php
	-rw-r--r--  1 apache apache  1733 Apr 19 17:29 userlist.php
	-rw-r--r--  1 apache apache  4806 Apr 19 17:29 userview.php

	
[root@linux ~]# cat /var/www/html/svnadmin/data/config.ini 
	[Common]
	FirstStart=0
	BackupFolder=./data/backup/

	[Translation]
	Directory=./translations/

	[Engine:Providers]
	AuthenticationStatus=ldap
	UserViewProviderType=ldap
	UserEditProviderType=
	GroupViewProviderType=ldap
	GroupEditProviderType=
	AccessPathViewProviderType=svnauthfile
	AccessPathEditProviderType=svnauthfile
	RepositoryViewProviderType=svnclient
	RepositoryEditProviderType=svnclient

	[ACLManager]
	UserRoleAssignmentFile=./data/userroleassignments.ini

	[Subversion]
	SVNAuthFile=/srv/svnrepo/ldap/

	[Repositories:svnclient]
	SVNParentPath=/srv/svnrepo
	SvnExecutable=/usr/bin/svn
	SvnAdminExecutable=/usr/bin/svnadmin

	[Users:passwd]
	SVNUserFile=

	[Users:digest]
	SVNUserDigestFile=
	SVNDigestRealm=

	[Ldap]
	HostAddress=ldap://192.168.1.10:389/
	ProtocolVersion=3
	BindDN=autent1@dominio.floresta
	BindPassword=
	CacheEnabled=false
	CacheFile=./data/ldap.cache.json

	[Users:ldap]
	BaseDN=DC=dominio,DC=floresta
	SearchFilter=(objectClass=user)
	Attributes=sAMAccountName

	[Groups:ldap]
	BaseDN=DC=dominio,DC=floresta
	SearchFilter=(objectClass=group)
	Attributes=sAMAccountName
	GroupsToUserAttribute=member
	GroupsToUserAttributeValue=distinguishedName

	[Update:ldap]
	AutoRemoveUsers=true
	AutoRemoveGroups=true

	[GUI]
	RepositoryDeleteEnabled=false
	RepositoryDumpEnabled=false
	AllowUpdateByGui=true
	[root@linux ~]# 

Logs http
		[Wed Apr 26 14:16:22.113219 2017] [:error] [pid 16119] [client 127.0.0.1:42598] PHP Warning:  ldap_search(): Search: Operations error in /var/www/html/svnadmin/include/ifcorelib/IF_AbstractLdapConnector.class.php on line 290, referer: http://localhost/svnadmin/settings.php
		[Wed Apr 26 14:18:02.175400 2017] [:error] [pid 16121] [client 127.0.0.1:42603] PHP Warning:  ldap_search(): Search: Operations error in /var/www/html/svnadmin/include/ifcorelib/IF_AbstractLdapConnector.class.php on line 290, referer: http://localhost/svnadmin/settings.php
		[Wed Apr 26 17:12:00.619265 2017] [:error] [pid 16122] [client 127.0.0.1:42681] PHP Warning:  ldap_search(): Search: Operations error in /var/www/html/svnadmin/include/ifcorelib/IF_AbstractLdapConnector.class.php on line 290, referer: http://localhost/svnadmin/settings.php

Thanks,

Armando

**Comment by mfreiholz** [comment]
Hi Armando
There are a few things in your configuration, which doesn't look right to me.

1. The `SVNAuthFile` should point to a file, not a directory.

```
[Subversion]
SVNAuthFile=/srv/svnauth.authz
```

2. Your LDAP `BindDN` looks invalid. It have to be a complete DN of a valid user.

```
[Ldap]
BindDN=CN=Administrator,CN=Users,DC=dominio,DC=floresta
```

Let me know, if my suggestions change something.

Best
Manuel

**Comment by armandoroque1** [comment]
Manuel,

Thanks for all!!!

Found 7 users.
Administrator, Guest, krbtgt, armandoroque, autent1, user1s1, *

 Found 23 groups.
WinRMRemoteWMIUsers__, Domain Computers, Domain Controllers, Schema Admins, Enterprise Admins, Cert Publishers, Domain Admins, Domain Users, Domain Guests, Group Policy Creator Owners, RAS and IAS Servers, Allowed RODC Password Replication Group, Denied RODC Password Replication Group, Read-only Domain Controllers, Enterprise Read-only Domain Controllers, Cloneable Domain Controllers, DnsAdmins, DnsUpdateProxy, sistema1, sistema2, sistema3, sistema4, sistema11
