### ISSUE TITLE
XML parse error: (code=5) Invalid document end

### ISSUE THREAD

**Issue by kiic-leung** [mfreiholz/iF.SVNAdmin#155]
Hi,

   When the repository's name is written with chinese characters，I  am unable to browser the repository content nor create the repository.

   【create repository】:
   ![image](https://user-images.githubusercontent.com/5969645/61762309-2aa3f080-ae04-11e9-91e5-3661787f29ae.png)

  【repository content browser】:
![image](https://user-images.githubusercontent.com/5969645/61762376-545d1780-ae04-11e9-8e7e-89055d5209d5.png)
   When click the repository to browser its content，I got error as follows:
   The error on WebUI --------  XML parse error: (code=5) Invalid document end
   
   and the network response html is broken:
   ![image](https://user-images.githubusercontent.com/5969645/61762742-8c188f00-ae05-11e9-9f8e-5a92fa3c6a1d.png)

   If repository's name is chinese，GetValue() function will return NULL，it won't run the condition:
   ![image](https://user-images.githubusercontent.com/5969645/61763049-8ec7b400-ae06-11e9-8d4c-61e900d43bd1.png)

  my environment is as under:
  OS: Ubuntu 16.04
  PHP 7.0.33-0ubuntu0.16.04.5 
  Apache/2.4.18 (Ubuntu)
  svnserve, version 1.9.3

**Comment by kiic-leung** [comment]
@mfreiholz

**Comment by xzplays** [comment]
应该是不支持中文目录。要转码的。

**Comment by kiic-leung** [comment]
> 应该是不支持中文目录。要转码的。
