### ISSUE TITLE
F.SVNAdmin support LDAPS with port 636 or 3269?

### ISSUE THREAD

**Issue by Burrunito** [mfreiholz/iF.SVNAdmin#158]
Hi Team.

I'd like to know if iF.SVNAdmin 1.6.2 support ldaps (636 or 3269 port) because this year Microsoft will force conexión only by secure ldaps protocol.

Regards.

**Comment by zhangqingwen** [comment]
I have the same question.

**Comment by Burrunito** [comment]
Hi zhangqingwen.

I answer to my question, in case I can help you, it works with both ports but there is a bug:
https://access.redhat.com/solutions/259573
You have to configure LDAPVerifyServerCert off in subversion.conf (/etc/httpd/conf.d) and TLS_REQCER never in ldap.conf (/etc/openldap) to not cheeck the remote certificate.

Regards.
