### ISSUE TITLE
Does iF.SVNAdmin support LDAPS

### ISSUE THREAD

**Issue by bedouino** [mfreiholz/iF.SVNAdmin#34]
Hi,

Does iF.SVNAdmin support LDAPS protocol (ldap + ssl) ?

If so where do you provide configuration information about certs files ?

Thanks,

nr

**Comment by dbcrvl** [comment]
Hi.

I am using iF.SVNAdmin (version 1.6.2 + apache2 on a Ubuntu machine) and I am currently using it with LDAP. All works great but I would like to know is it possible to use LDAPS instead and, mainly, how to configure it?

Thanks,

**Comment by jorritsmit** [comment]
Old comment but wanted to mention that you can set this up by entering the url like this:
ldaps://url:636. Also as mentioned above if you have a custom certificate you have to set TLS_REQCERT to never in /etc/openldap/ldap.conf. BUT if you can get the certificate authority for your server you can add it in ldap.conf as follows:  TLS_CACERT /path/to/ca.pem
