### ISSUE TITLE
Ldap Users Display Name

### ISSUE THREAD

**Issue by portilha** [mfreiholz/iF.SVNAdmin#57]
Hi,

I don't know if this is possible already, but i think not...
I would like to display on the User List another attribute of the ldap object instead of the sAMAccountName, but saving the sAMAccountName in the SVNAuthFile.
If this is possible already please let me know ..

Thanks, great software..

**Comment by marceliusvb** [comment]
Hi:

I´m very interested to test this valuable tip. I´m user of this great software in a big Company in Brazil. 

Whitch option set this settings ?

Context Menu -> TortoiseSVN -> Settings -> General -> Subversion Configuration File ????

Thanks a lot.

**Comment by mfreiholz** [comment]
Hey @marceliusvb 
Is it possible that you commented on the wrong project? This is not about TortoiseSVN. All configurations are on the server in `data/config.ini` file.

**Comment by marceliusvb** [comment]
Yes. It is.
Thanks for explain that
