### ISSUE TITLE
Exception list error

### ISSUE THREAD

**Issue by karnivpatel** [mfreiholz/iF.SVNAdmin#85]
Hello everyone,

I am using Ubuntu 14.04 LTS.
I was successful install iF.SVNadmin & GUI is working fine.
But i have 2 issues which are :
1. When add Repository then it's add into Access-Paths list but not add in under Repositories list & when check with terminal then nothing is added in to that directory.
2. When click any existing repository to show documents then it's show me error " Exception list : XML parse error: (code=5) Invalid document end "

Setting of GUI
Subversion authorization file : /etc/svndirectory
User authentication file (SVNUserFile) : /etc/svnpasswd
Parent directory of the repositories (SVNParentPath) : /var/www/html/svn/
Subversion client executable : /var/www/html/svnadmin/user.sh
Subversion admin executable : /var/www/html/svnadmin/admin.sh

#/etc/apache2/sites-available/testrepo.conf
<Location /svn>
  DAV svn
  SVNParentPath /var/www/html/svn/
  AuthType Basic
  AuthName "Test Repo"
  AuthUserFile /etc/svnpasswd
  Require valid-user
</Location>

Can i missing anything?
Any help would be appriciated.
Thanks in advance.

Thanks
Karniv Patel

**Comment by mfreiholz** [comment]
Hi

Can you check,  that your apache user does have write permission on your
repository parent directory?

Manuel

Sent from mobile.
Am 02.02.2015 13:45 schrieb "karnivpatel" <notifications@github.com>:

**Comment by karnivpatel** [comment]
Hi mfreiholz,
Thanks for quick reply,

apache user have full permission on repository parent directory.
#ll
drwxrwxrwx  3 root apache    4096 Jan 23 22:31 svn/

# ll
total 12
drwxrwxrwx 3 root apache 4096 Jan 23 22:31 ./
drwxr-xr-x 7 root root   4096 Feb  2 12:47 ../
drwxrwxrwx 7 root apache 4096 Jan 29 15:11 project_repo/

**Comment by mfreiholz** [comment]
Do you have SELinux activated? It sometimes blocks the "svnadmin create"
and "svn list"  commands.

Is there any special magic in your svn.sh or svnadmin.sh scripts which
could cause any problems?

Usually every problem with command line execution should appear in the
apache error log.

Manuel

Sent from mobile.
Am 03.02.2015 07:13 schrieb "karnivpatel" <notifications@github.com>:

**Comment by karnivpatel** [comment]
No any SELinux policy in existing system

Not any magic in 
Subversion client executable : /var/www/html/svnadmin/user.sh
Subversion admin executable : /var/www/html/svnadmin/admin.sh
If i am not mention that two files in setting then repository is not create.
But i don't know what exactly do this two files so i see your screenshots & create that two files.
Please you guide me what exaclty do that two files "client & admin" executable & which file mention in that. 

#tail -f /var/log/apache2/error.log

[:error] [pid 1532] [client 192.168.1.XX:39331] PHP Fatal error:  Call to a member function getEncodedParentIdentifier() on a non-object in /var/www/html/svnadmin/pages/repository/repositoryview.html.php on line 5, referer: http://192.168.1.XX/svnadmin/repositorylist.php

[:error] [pid 1536] [client 192.168.1.XX:39344] PHP Fatal error:  Call to a member function getEncodedParentIdentifier() on a non-object in /var/www/html/svnadmin/pages/repository/repositoryview.html.php on line 5, referer: http://192.168.1.XX/svnadmin/repositorylist.php

[mpm_prefork:notice] [pid 1459] AH00163: Apache/2.4.7 (Ubuntu) SVN/1.8.8 PHP/5.5.9-1ubuntu4.5 
configured -- resuming normal operations

[core:notice] [pid 1459] AH00094: Command line: '/usr/sbin/apache2'

[:error] [pid 1487] [client 192.168.1.XX:58382] PHP Fatal error:  Call to a member function getEncodedParentIdentifier() on a non-object in /var/www/html/svnadmin/pages/repository/repositoryview.html.php on line 5, referer: http://192.168.1.XX/svnadmin/repositorylist.php

**Comment by mfreiholz** [comment]
Oooooh now i see.

You need to install "subversion" on your server (you probably already did that) and instead of pointing to some "*.sh" scripts, you need to point these paths to the installed binaries on your server. The web application uses the normal command line programs of subversion to get SVN related information.

They are usually located here:
`/usr/bin/svn`
`/usr/bin/svnadmin`

You can find out by `whereis svn` and `whereis svnadmin`

**Comment by karnivpatel** [comment]
Hello
Thanks for your support 

Now repository working fine.
But i get one other issue
I can create user, but i cann't login with that user, i got error "Exception list : Wrong user/password combination.", I don't get any error in log file.

User authentication file (SVNUserFile) : /etc/svnpasswd

# cat /etc/svnpasswd 
admin:$apr1$B7uTfRSS$MblEzOAGdvhvyxebkTocq0
user1:$apr1$rCg8UDFM$qYH2G4CzCKDL6eZCUHF2R1

**Comment by mfreiholz** [comment]
Hm that's weird... Looks good to me.
What's the plain password for "user1"? Or can you create a user, post the line from svnpasswd file and tell me the plain password, please? I'd like to validate the hash.

**Comment by karnivpatel** [comment]
admin : admin
user1 : user1
user2 : user 2

#cat /etc/svnpasswd 
admin:$apr1$B7uTfRSS$MblEzOAGdvhvyxebkTocq0
user1:$apr1$rCg8UDFM$qYH2G4CzCKDL6eZCUHF2R1
user2:$apr1$LeDG1S6x$GlEWVdTmmmEH1/XC8qBgh/

**Comment by mfreiholz** [comment]
Hm... i validated the hashes with OpenSSL. They are OK.

but another idea. Did you already assign the an Role to the users? You can only login with a user to the web interface, if he is allowed to by Role. The admin user should already have the "Administrator" role, it has been assigned during setup.

In case you want to reset roles, you can delete the `data/userroleassignments.ini` file.

**Comment by karnivpatel** [comment]
Thanks a lot 
Thank you very much

My issue has been resolved.

**Comment by mfreiholz** [comment]
Great!
