### ISSUE TITLE
Unknown error occured

### ISSUE THREAD

**Issue by karnivpatel** [mfreiholz/iF.SVNAdmin#86]
Hello everyone,
First of all. Fine tool. Thanks for that.

I am using Ubuntu 14.04 LTS.
I was successful install iF.SVNadmin & GUI is working fine.
But i have 1 issues which is :
I create one user (i.e karniv) now admin give permission to karniv (Repository-Creator - Can create new repositories, but NOT delete.), Now karniv create any repository (i.e Test1), Now admin add access path 
Access-Path >> Add >> Browse >> Select Test1 >> Create
Then it's give error "An unknown error occured. Check your configuration, please."

![svnadmin](https://cloud.githubusercontent.com/assets/10459006/6225946/7db52e6e-b6b6-11e4-8bb4-068a75fa165b.png)
 
Setting of GUI
Subversion authorization file : /etc/svndirectory
User authentication file (SVNUserFile) : /etc/svnpasswd
Parent directory of the repositories (SVNParentPath) : /var/www/html/svn/
Subversion client executable : /usr/bin/svn/
Subversion admin executable : /usr/bin/svnadmin/

#/etc/apache2/sites-available/testrepo.conf
DAV svn
SVNParentPath /var/www/html/svn/
AuthType Basic
AuthName "Test Repo"
AuthUserFile /etc/svnpasswd
Require valid-user

Can i missing anything?
Any help would be appriciated.
Thanks in advance.

Thanks
Karniv Patel

**Comment by mfreiholz** [comment]
Looks like, the application doesn't have access to your authorization file (`/etc/svndirectory`). Your Apache `error.log` is probably showing you a permission denied error. Can you check this, please?

Manuel

**Comment by karnivpatel** [comment]
# tail -f /var/log/apache2/error.log
PHP Warning:  chmod(): Operation not permitted in /var/www/html/svnadmin/include/ifcorelib/IF_SVNAdminC.class.php on line 118
PHP Warning:  chmod(): Operation not permitted in /var/www/html/svnadmin/include/ifcorelib/IF_SVNAdminC.class.php on line 118

# ll /etc/svndirectory 
-rwxrwxrwx 1 root root 306 Feb 17 15:01 /etc/svndirectory*

Otherwise i got error "An unknown error occured. Check your configuration, please.".

Thanks,
Karniv Patel

**Comment by mfreiholz** [comment]
The `chmod` only happens on repository deletion. Did you also `tail -f` during the creation of an Access Path?

**Comment by karnivpatel** [comment]
Thanks for Reply,

Yes, I do tail -f During the creation of Acess Path.

Thanks
Karniv Patel

**Comment by mfreiholz** [comment]
Weird. Based on code this can only happen, when the access-path already exists in authz-file.

https://github.com/mfreiholz/iF.SVNAdmin/blob/master/include/ifcorelib/IF_SVNAuthFileC.class.php#L363

Every other error would throw an exception and would be visible in UI.

Dumb question: Does the path already exist in file?

```ini
# Repo root
[myrepo:/]

# Sub directory
[myrepo:/awesome/code/down/here]
```

Manuel

**Comment by karnivpatel** [comment]
Hello Manuel,
Thanks for Reply,

I got the solution

Thanks
Karniv Patel

**Comment by mfreiholz** [comment]
May i ask you: How did you fix it? What was the problem?

Manuel

**Comment by karnivpatel** [comment]
Sure...why not...
It was my mistake,

In my above example, karniv(Repository-Creator) add new repository(Test1), then after administrator browse that repository(Test1) from access path, but that repository(Test1) was already exits in access path, so it's give me error.

Thanks,
Karniv Patel

**Comment by mfreiholz** [comment]
Well, a better error message from the application would have save us a lot of time.

Thanks.

----- Ursprüngliche Nachricht -----
Von: "karnivpatel" <notifications@github.com>
Gesendet: ‎26.‎02.‎2015 10:30
An: "mfreiholz/iF.SVNAdmin" <iF.SVNAdmin@noreply.github.com>
Cc: "Manuel Freiholz" <manuel@insanefactory.com>
Betreff: Re: [iF.SVNAdmin] Unknown error occured (#86)

Sure...why not...
It was my mistake,
In my above example, karniv(Repository-Creator) add new repository(Test1), then after administrator browse that repository(Test1) from access path, but that repository(Test1) was already exits in access path, so it's give me error.
Thanks,
Karniv Patel
