### ISSUE TITLE
page cant diplay 

### ISSUE THREAD

**Issue by birotee** [mfreiholz/iF.SVNAdmin#93]
error in log file as below and page can't display 
[Thu Apr 23 14:02:11 2015] [error] [client 10.21.6.245] PHP Warning:  Unexpected character in input:  '\\' (ASCII=92) state=1 in /var/www/html/svnadmin/include/config.inc.php on line 146
[Thu Apr 23 14:02:11 2015] [error] [client 10.21.6.245] PHP Warning:  Unexpected character in input:  '\\' (ASCII=92) state=1 in /var/www/html/svnadmin/include/config.inc.php on line 146
[Thu Apr 23 14:02:11 2015] [error] [client 10.21.6.245] PHP Parse error:  syntax error, unexpected T_STRING in /var/www/html/svnadmin/include/config.inc.php on line 146

**Comment by mfreiholz** [comment]
Which PHP version is running on your server?

**Comment by birotee** [comment]
PHP 5.1.6 (cli) (built: Feb 11 2010 19:06:40)

**Comment by mfreiholz** [comment]
You need >=5.3
