### ISSUE TITLE
Add groups to another groups

### ISSUE THREAD

**Issue by joubertredrat** [mfreiholz/iF.SVNAdmin#95]
Hi,

I was to start the feature to add and remove groups from other groups, however, I saw that you are developing version 2 of iF.SVNAdmin

Version 1.X will be discontinued? I was going to start developing this feature today to make the pull request in a few weeks, however, if the 1.x version will not continue, I don't know if I should develop this resource and then publish.

**Comment by mfreiholz** [comment]
Hi joubertredrat,

V2 already supports groups as members of other groups.
I don't know if you need it, but the current implementation of V2 doesn't have any role or project management and i'm not sure, if i will add it soon or anyway. I'd like to keep the application simple with it's core functionality: Repository- + user management.

I did not plan to build new features for V1, only upcoming bug fixes.

I'll check the current progress of V2 (it's a while ago). As far as i can remember, it is already usable with it's core functionality.

Manuel

**Comment by joubertredrat** [comment]
Hi @mfreiholz 

Then I can make pull request on this repo when this feature is finished? I finished first step from this yestestday.

https://github.com/vectornet/iF.SVNAdmin/tree/feature-groups

**Comment by mfreiholz** [comment]
Yes, but please make sure that you are using the correct line endings and
tab/spaces settings. I dont want a pull request which touches every file ;)

Sent from mobile phone.
Am 28.05.2015 13:24 schrieb "Joubert RedRat" <notifications@github.com>:

**Comment by joubertredrat** [comment]
Hi @mfreiholz,

It's done, are you want to test before I make PR?
https://github.com/vectornet/iF.SVNAdmin/tree/feature-groups

**Comment by mfreiholz** [comment]
You can make the PR and i will test it before merge.

Sent from mobile phone.
Am 28.05.2015 22:07 schrieb "Joubert RedRat" <notifications@github.com>:

**Comment by joubertredrat** [comment]
It's done @mfreiholz 

Now is possible to assign groups in group on members page and assign and unassign groups on groupview page.
